### ISSUE TITLE
Output is escape by default

### ISSUE THREAD

**Issue by timiti29** [trsteel88/TrsteelCkeditorBundle#104]
I use Symfony 3.0.4-dev and TrsteelCkeditorBundle v1.10.4.
When i write text on the field, for exemple : "`toto`", after submit the form i get the content : "`&lt;p&gt;toto&lt;/p&gt;`".
if i type "`toto`" and i click on the "Source" button, he show me the html source : "`<p>toto</p>`"
and if i submit the form i get "`<p>toto</p>`"

Why ?

**Comment by trsteel88** [comment]
Ckeditor will automatically wrap your text with a <p> tag.
