### ISSUE TITLE
Expose the config.allowedContent option

### ISSUE THREAD

**Issue by erichard** [trsteel88/TrsteelCkeditorBundle#106]
The bundle use two filtering system : [Ckeditor ACF](http://docs.ckeditor.com/#!/guide/dev_acf) and the htmlpurifier. 

I think the ACF should be disabled or at least optionnaly disabled. 

The CkEditor documentation tell us to set  `config.allowedContent = true`.

**Comment by trsteel88** [comment]
I'm not sure what you mean by optionally disabled. If you want to disable
it, just set that in your config?

**Comment by erichard** [comment]
This option is not exposed in the bundle config yet

**Comment by malas** [comment]
bundle config must have this option available. because with 'extra_allowed_content' we can not disable ACF.

**Comment by nashsaint** [comment]
Can't figure out how to add this to config.yml

Attr.AllowedFrameTargets = true

**Comment by trsteel88** [comment]
allowedContent is now supported in v1.11.0

See https://github.com/trsteel88/TrsteelCkeditorBundle/commit/aa80a1642af723511794d11b3ff192e543a1219a
