### ISSUE TITLE
Configuration for plug-ins

### ISSUE THREAD

**Issue by AdamReece-WebBox** [trsteel88/TrsteelCkeditorBundle#111]
Is it possible to provide configuration options for plug-ins?

For example the [YouTube plug-in](https://ckeditor.com/cke4/addon/youtube) has many configurable defaults for video insertion. I'd like to have the responsive width enabled by default.

If not I would suggest this feature be implemented by allowing for a flexible "config" node alongside the "path" and "file" nodes of "external_plugins" children. For example:

    external_plugins:
        youtube:
            path:   js/ckeditor/plugins/youtube
            config:
                youtube_responsive: true

**Comment by trsteel88** [comment]
I usually load a custom config.js through custom_config and then customise the options within there.
