### ISSUE TITLE
Image Upload issue

### ISSUE THREAD

**Issue by brainwood** [trsteel88/TrsteelCkeditorBundle#112]
Hi, 

After the update I am having trouble with uploading images. The initial error was that I was still using old CKEditorFuncNum responses but I have since updated to the new responses as per this documentation https://ckeditor.com/docs/ckeditor4/latest/guide/dev_file_upload.html#request

I no longer get a dialog box with server error on the upload but it also doesn't switch to the "Image Info" tab with the image and doesn't insert the image into the editor.

Thank you for your time

**Comment by trsteel88** [comment]
What are you using to handle file uploads and what does the response look like when the file is uploaded?

**Comment by brainwood** [comment]
Thank you so much for your response.
I just removed and re-installed this as a dependency and it seems to be working correctly now. 
Not sure what would have caused the issue in the first place but thank you for taking the time to respond and be available to help.
