### ISSUE TITLE
Plugin breaks when dragged&dropped by Jquery UI Sortable

### ISSUE THREAD

**Issue by ioleo** [trsteel88/TrsteelCkeditorBundle#53]
After dragging & dropping with Jquery UI Sortable the plugin goes dead. The content disappears only an empty ckeditor shell (not working buttons, white content space).

Does anyone have an idea how to fix it? Is it CKEditor issue, or the way TrsteelCkeditorBundle initiates Ckeditor could affect this?

**Comment by arpita-hunka** [comment]
I have another type of element along with CKEditor, I used the above code and that is working when I move the CKEditor but when i move other elements at that time CKEditor content lost. @ioleo Can you please help to fix this?
